default:
  image: golang:1.20

stages:
  - test
  - build
  - deploy

build-binaries-job:
  image: golang:1.20
  stage: build
  script:
    - make build

build-docker-images-job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  environment:
    DOCKER_BUILDKIT: 1
    NAME: display-parser
  script:
    - docker build -t ${NAME}-app:latest --target=app-image -f Dockerfile .
    - docker build -t ${NAME}-http:latest --target=http-image -f Dockerfile .

lint-test-job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: test
  script:
    - pwd
    - ls -la
    - docker run --rm -v $(pwd):/app -v ~/.cache/golangci-lint/v1.53.3:/root/.cache -w /app golangci/golangci-lint:v1.53.3 golangci-lint run -v

unit-test-job:
  image: golang:1.20
  stage: test
  script:
    - make test
