default:
  image: golang:1.20
variables:
  # When you use the dind service, you must instruct Docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/services/#accessing-the-services.
  #
  # Specify to Docker where to create the certificates. Docker
  # creates them automatically on boot, and creates
  # `/certs/client` to share between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"
stages:
  - test
  - build
  - deploy

build-binaries-job:
  image: golang:1.20
  stage: build
  script:
    - make build

build-docker-images-job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  script:
    - DOCKER_BUILDKIT=1 docker build -t display-parser-app:latest --target=app-image -f Dockerfile .
    - DOCKER_BUILDKIT=1 docker build -t display-parser-http:latest --target=http-image -f Dockerfile .

push-docker-images-job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: build
  script:
    # APP
    - docker tag display-parser-app 192.168.1.47:5000/display-parser-app
    - docker push 192.168.1.47:5000/display-parser-app
    # HTTP
    - docker tag display-parser-http 192.168.1.47:5000/display-parser-http
    - docker push 192.168.1.47:5000/display-parser-http

lint-test-job:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: test
  script:
    - pwd
    - ls -la
    - docker run --rm -v $(pwd):/app -v ~/.cache/golangci-lint/v1.53.3:/root/.cache -w /app golangci/golangci-lint:v1.53.3 golangci-lint run -v

unit-test-job:
  image: golang:1.20
  stage: test
  script:
    - make test
