secrets:
  postgres_password:
    environment: "postgres"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "${display_parser-postgres_password}"

  app:
    image: display_parser
    build:
      context: .
      dockerfile: Dockerfile


