FROM golang:1.20 AS install
COPY ./Makefile /src/Makefile
WORKDIR /src
RUN --mount=type=cache,target=/go/src make install-dev-tools


FROM ubuntu:latest AS sql-migrate-image
COPY --from=install /go/bin/sql-migrate /usr/local/bin/sql-migrate

FROM ubuntu:latest AS golangci-lint-image
COPY --from=install /go/bin/golangci-lint /usr/local/bin/golangci-lint
