services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: display_parser
      POSTGRES_PASSWORD: display_parser
      POSTGRES_DB: display_parser
    expose:
      - 5432

  http:
    image: display_parser-http
    build:
      context: .
      dockerfile: Dockerfile
      target: http-image
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "3000:3000"
    command:
      - bin/http
      - --db-user=display_parser
      - --db-password=display_parser
      - --db-hostname=postgres
      - --db-port=5432
      - --db-name=display_parser
      - --cors-allowed-origin=http://localhost:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs/openapi.yml:/openapi.yml
    environment:
      SWAGGER_JSON: /openapi.yml
    ports:
      - 8080:8080
#  app:
#    image: display_parser-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: app-image
#    depends_on:
#      - postgres
#    links:
#      - postgres:postgres
#    command:
#      - make
#      - run